'use client';

import { AnimatePresence, motion, useScroll, useSpring, useTransform } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import type { CSSProperties, ElementType } from 'react';
import { EASE_OUT } from '@/lib/ease';
import { cx } from '@/lib/utils';

function prefersReducedMotion() { return typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches; }
export function useInView<T extends HTMLElement>(options?: { once?: boolean; amount?: number; rootMargin?: string }) {
  const ref = useRef<T | null>(null); const [inView, setInView] = useState(false);
  useEffect(() => { const el = ref.current; if (!el) return; if (prefersReducedMotion()) { setInView(true); return; } if (!('IntersectionObserver' in window)) { setInView(true); return; }
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { setInView(true); if (options?.once !== false) observer.unobserve(entry.target); } else if (options?.once === false) setInView(false); }), { threshold: options?.amount ?? .18, rootMargin: options?.rootMargin ?? '0px 0px -8% 0px' }); observer.observe(el); return () => observer.disconnect();
  }, [options?.amount, options?.once, options?.rootMargin]); return { ref, inView } as const;
}

type RevealVariant = 'up'|'mask'|'scale';
interface RevealProps extends React.HTMLAttributes<HTMLElement>{children:React.ReactNode;delay?:number;variant?:RevealVariant;as?:ElementType;className?:string}
export function Reveal({children,delay=0,variant='up',as,className,style,...rest}:RevealProps){const {ref,inView}=useInView<HTMLDivElement>();const Comp:ElementType=as??'div';const variantClass=variant==='mask'?'reveal--mask':variant==='scale'?'reveal--scale':'';const merged:CSSProperties={['--reveal-delay' as string]:`${delay}s`,...style};return <Comp ref={ref} className={cx('reveal',variantClass,className)} data-inview={inView?'true':'false'} style={merged} {...rest}>{children}</Comp>}

export function SplitChars({text,className,delay=0,step=.022}:{text:string;className?:string;delay?:number;step?:number}){const {ref,inView}=useInView<HTMLSpanElement>();let index=0;return <span ref={ref} className={className} data-inview={inView?'true':'false'} aria-label={text}>{text.split(' ').map((word,wi)=><span key={`${word}-${wi}`} style={{display:'inline-block',whiteSpace:'nowrap'}} aria-hidden="true">{Array.from(word).map((char,ci)=>{const d=delay+index++*step;return <span key={`${char}-${ci}`} className="split-char" style={{['--char-delay' as string]:`${d}s`}}>{char}</span>})}{wi<text.split(' ').length-1&&<span className="split-char" style={{['--char-delay' as string:`${delay+index++*step}s`}}>&nbsp;</span>}</span>)}</span>}
export function SplitLines({lines,className,delay=0,step=.11}:{lines:React.ReactNode[];className?:string;delay?:number;step?:number}){const {ref,inView}=useInView<HTMLSpanElement>();return <span ref={ref} className={className} data-inview={inView?'true':'false'} style={{display:'block'}}>{lines.map((line,i)=><span className="split-line" key={i}><span style={{['--line-delay' as string]:`${delay+i*step}s`}}>{line}</span></span>)}</span>}

export function Counter({to,duration=1.8,suffix='',prefix='',decimals=0,className}:{to:number;duration?:number;suffix?:string;prefix?:string;decimals?:number;className?:string}){const {ref,inView}=useInView<HTMLSpanElement>();const node=useRef<HTMLSpanElement>(null);useEffect(()=>{if(!inView||!node.current)return;const reduced=prefersReducedMotion();if(reduced){node.current.textContent=`${prefix}${to.toFixed(decimals)}${suffix}`;return;}let raf=0;const start=performance.now();const tick=(now:number)=>{const p=Math.min(1,(now-start)/(duration*1000));const eased=1-Math.pow(1-p,3);if(node.current)node.current.textContent=`${prefix}${(to*eased).toFixed(decimals)}${suffix}`;if(p<1)raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[decimals,duration,inView,prefix,suffix,to]);return <span ref={(el)=>{node.current=el;ref.current=el}} className={cx('num',className)}>{prefix}0{suffix}</span>}

export function Marquee({items,duration=34,reverse=false,className}:{items:string[];duration?:number;reverse?:boolean;className?:string}){const content=<div className="marquee__track" style={{['--marquee-dur' as string]:`${duration}s`}} aria-hidden="true">{items.map((item,i)=><span className="marquee__item" key={`${item}-${i}`}>{item}<span className="dotsep">&#9679;</span></span>)}</div>;return <div className={cx('marquee',reverse&&'marquee--reverse',className)}>{content}{content}</div>}
export function Parallax({children,distance=80,className}:{children:React.ReactNode;distance?:number;className?:string}){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const y=useSpring(useTransform(scrollYProgress,[0,1],[distance,-distance]),{stiffness:90,damping:24,mass:.4});return <div ref={ref} className={className}><motion.div style={{y}}>{children}</motion.div></div>}
export function ScrollScale({children,className}:{children:React.ReactNode;className?:string}){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start end','center center']});const scale=useSpring(useTransform(scrollYProgress,[0,1],[1.14,1]),{stiffness:80,damping:22});return <div ref={ref} className={className}><motion.div style={{scale}}>{children}</motion.div></div>}
export function Rotator({words,interval=2600,className}:{words:string[];interval?:number;className?:string}){const [i,setI]=useState(0);useEffect(()=>{if(words.length<2||prefersReducedMotion())return;const id=setInterval(()=>setI((prev)=>(prev+1)%words.length),interval);return()=>clearInterval(id)},[interval,words.length]);return <span className={cx('hero__rotator',className)} aria-live="polite"><AnimatePresence mode="wait" initial={false}><motion.span key={words[i]} initial={{y:'105%',opacity:0}} animate={{y:'0%',opacity:1}} exit={{y:'-105%',opacity:0}} transition={{duration:.62,ease:EASE_OUT}}>{words[i]}</motion.span></AnimatePresence></span>}
